# Day 11–13: Python + SQL Integration

## Objective
Connect Python with SQLite and answer business questions using SQL queries executed through Pandas.

### Skills Covered
- SQLite Database Connection
- SQL Query Execution
- Business Analysis
- Data Retrieval using Pandas
- Insight Generation

In [36]:
import sqlite3
import pandas as pd
conn=sqlite3.connect("cleaned_superstore.db")
print("Database connected sucessfully")

Database connected sucessfully

## Step 2: Verify Available Tables

Before querying data, it is important to check which tables exist in the database.

In [37]:
q = """
SELECT name
FROM sqlite_master
WHERE type='table'
"""

pd.read_sql(q, conn)

    name
0  sales

## Step 3: Business Questions & Insights

## Business Question 1: Top 5 Products by Total Sales

### Objective
Identify the products generating the highest sales revenue.

In [38]:
q="""
SELECT
    [Product Name],
    SUM(Sales) AS Total_Sales
FROM sales
GROUP BY [Product Name]
ORDER BY Total_Sales DESC
LIMIT 5
"""

pd.read_sql(q,conn)

                                        Product Name  Total_Sales
0                                    Staple envelope     1438.972
1                                  Easy-staple paper     1374.532
2                                            Staples      755.470
3  Logitech B530 USB Headset - headset - Full siz...      628.830
4  Logitech 910-002974 M325 Wireless Mouse for We...      545.818

## Business Question 2: Sales by Region

### Objective
Determine which region contributes the highest sales.

In [39]:
q="""
SELECT
    Region,
    SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Region
ORDER BY Total_Sales DESC
"""

pd.read_sql(q,conn)

    Region  Total_Sales
0     West   59455.3060
1     East   53563.9190
2  Central   39252.2134
3    South   29526.0880

## Business Question 3: Category Performance

### Objective
Compare sales across product categories.

In [40]:
q="""
SELECT
    Category,
    SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Category
ORDER BY Total_Sales DESC
"""

pd.read_sql(q,conn)

          Category  Total_Sales
0  Office Supplies  124337.4610
1        Furniture   28973.2084
2       Technology   28486.8570

## Business Question 4: Most Profitable Category

### Objective
Identify categories generating the highest profit.

In [41]:
q="""
SELECT
    Category,
    SUM(Profit) AS Total_Profit
FROM sales
GROUP BY Category
ORDER BY Total_Profit DESC
"""

pd.read_sql(q,conn)

          Category  Total_Profit
0  Office Supplies    24316.6685
1       Technology     4479.5425
2        Furniture     2355.4676

## Business Question 5: Average Order Value by Region

### Objective
Measure average sales value per order in each region.

In [42]:
q="""
SELECT
    Region,
    AVG(Sales) AS Avg_Order_Value
FROM sales
GROUP BY Region
ORDER BY Avg_Order_Value DESC
"""

pd.read_sql(q,conn)

    Region  Avg_Order_Value
0     West        31.457834
1     East        30.678075
2    South        29.824331
3  Central        26.958938

## Business Question 6: Top 10 Customers by Sales

### Objective
Identify the customers generating the highest revenue.

In [43]:
q="""
SELECT
    [Customer Name],
    SUM(Sales) AS Total_Sales
FROM sales
GROUP BY [Customer Name]
ORDER BY Total_Sales DESC
LIMIT 10
"""
pd.read_sql(q,conn)

         Customer Name  Total_Sales
0     Jonathan Doherty      879.466
1            Ken Black      798.222
2      Chris Selesnick      794.144
3        William Brown      777.433
4          Roger Demir      707.367
5      Patrick Gardner      691.585
6          Dean percer      690.423
7         Edward Hooks      669.124
8  Chloris Kastensmidt      654.735
9            Greg Tran      634.976

## Business Question 7: Sales by Customer Segment

### Objective
Compare sales across customer segments.

In [44]:
q="""
SELECT
    Segment,
    SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Segment
ORDER BY Total_Sales DESC
"""
pd.read_sql(q,conn)

       Segment  Total_Sales
0     Consumer   93608.3508
1    Corporate   55464.0202
2  Home Office   32725.1554

## Business Question 8: Top Cities by Sales

### Objective
Identify cities generating the highest revenue.

In [45]:
q="""
SELECT
    City,
    SUM(Sales) AS Total_Sales
FROM sales
GROUP BY City
ORDER BY Total_Sales DESC
LIMIT 10
"""
pd.read_sql(q,conn)

            City  Total_Sales
0  New York City   17621.8380
1    Los Angeles   13616.4500
2  San Francisco    9966.8500
3   Philadelphia    9610.9640
4        Seattle    7942.3960
5        Houston    6660.8696
6        Chicago    5111.2810
7       Columbus    4226.6930
8      San Diego    3346.7340
9    Springfield    3114.7190

## Business Question 9: Average Profit by Discount Level

### Objective
Analyze how discounts affect profitability.

In [46]:
q="""
SELECT
    Discount,
    AVG(Profit) AS Avg_Profit
FROM sales
GROUP BY Discount
ORDER BY Discount
"""
pd.read_sql(q,conn)

   Discount  Avg_Profit
0      0.00   11.439837
1      0.10   13.566567
2      0.20    5.977193
3      0.30   -7.285856
4      0.32  -13.874033
5      0.40  -10.121646
6      0.50  -35.823945
7      0.60  -18.797955
8      0.70  -14.832166
9      0.80  -28.930656

## Business Question 10: Profit by Region

### Objective
Compare profitability across regions.

In [47]:
q="""
SELECT
    Region,
    SUM(Profit) AS Total_Profit
FROM sales
GROUP BY Region
ORDER BY Total_Profit DESC
"""
pd.read_sql(q,conn)

    Region  Total_Profit
0     West    15206.7966
1     East    12065.2227
2    South     5907.1611
3  Central    -2027.5018

# Conclusion

This notebook demonstrated how Python and SQL can be integrated to answer real-world business questions.

### Key Skills Demonstrated
- SQLite Database Connectivity
- SQL Query Execution with Pandas
- Business Data Analysis
- Revenue Analysis
- Customer Analysis
- Regional Performance Analysis
- Profitability Assessment

### Outcome
Successfully answered 10 business questions using SQL queries executed through Python, generating actionable business insights from the Superstore dataset.

In [48]:
conn.close()